### ISSUE TITLE
Maven 403 Forbidden 

### ISSUE THREAD

**Issue by larrynikx** [Orange-OpenSource/spring-boot-autoconfigure-proxy#1]
```
Failed to collect dependencies at com.orange.common:spring-boot-autoconfigure-proxy:jar:1.0.1:
Failed to read artifact descriptor for com.orange.common:spring-boot-autoconfigure-proxy:jar:1.0.1: 

Could not transfer artifact com.orange.common:spring-boot-autoconfigure-proxy:pom:1.0.1 from/to bintray-orange (http://dl.bintray.com/orange-opensource/maven): Authorization failed for http://dl.bintray.com/orange-opensource/maven/com/orange/common/spring-boot-autoconfigure-proxy/1.0.1/spring-boot-autoconfigure-proxy-1.0.1.pom 

403 Forbidden
```

**Comment by larrynikx** [comment]
Seems the bintray link is broken. Had to fork this and self host.

**Comment by sag1** [comment]
@pismy Hello Pierre Could you please fix this issue ?

**Comment by Guilamb** [comment]
thanks @larrynikx for the workaround !

Was useful to get the closed-source burger-maker tutorial working. Here is the corresponding patch to use your self hosted version on mymavenrepo.com
https://gist.github.com/Guilamb/99c535a4941893002445b0e78e4adfea

**Comment by pismy** [comment]
Unfortunately bintray has been discontinued, that's why it is not longer possible to download the Maven dependency from there.

I wanted to use [GitHub Maven registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) but I couldn't get it working :( (constantly obtaining a `401 Unauthorized`).

Do you guys have another idea of an alternate public Maven repository I could use ?

**Comment by sag1** [comment]
Hello @pismy It's problem of github credentials, strange behavior, project settings are not taken into account while publishing. I added the server id as below in the global user settings and it works.  It publishs correctly without 401 Unauthorized.
  ```
<servers>
      <server>
            <id>github</id>
            <username>${env.GITHUB_USERNAME}</username>
            <password>${env.GITHUB_TOKEN}</password>
        </server>
    </servers>
```

**Comment by sag1** [comment]
@larrynikx @Guilamb I close this issue as I managed to publish on Github Maven Registry. Refer `README` to use it in your projects
